# Generated by Django 5.0.1 on 2024-02-03 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_user_alter_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='color_id',
        ),
        migrations.AddField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.color'),
        ),
    ]
