# Generated by Django 5.0.1 on 2024-02-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_cartdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='state_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
