# Generated by Django 5.0.1 on 2024-02-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cart_state_id_cart_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='account_id',
            new_name='account',
        ),
    ]
