# Generated by Django 5.0.1 on 2024-02-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_account_id_cart_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='order_id',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='cart_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cart'),
        ),
    ]
