# Generated by Django 5.0.1 on 2024-02-07 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_cart_id_cartdetail_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='size_id',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_details', to='app.cart'),
        ),
    ]
