# Generated by Django 5.0.1 on 2024-02-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_cartdetail_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accept_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='account',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship_id',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='state_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='size_id',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sample_id',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='size_id',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='accept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_accounted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_shipped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
