# Generated by Django 5.0.1 on 2024-02-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_order_accept_id_remove_order_account_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='accept',
            new_name='accept_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='state_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='color',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='size',
            new_name='size_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='ship_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_shipped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sample'),
        ),
        migrations.AddField(
            model_name='product',
            name='state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.state'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.size'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship',
            field=models.IntegerField(null=True),
        ),
    ]
