# Generated by Django 5.0.1 on 2024-02-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_accept_order_accept_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='account_id',
        ),
    ]
