# Generated by Django 5.0.1 on 2024-02-20 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_cart_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_details', to='app.cart'),
        ),
    ]
