# Generated by Django 5.0.1 on 2024-02-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_cartdetail_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ship',
        ),
    ]
