# Generated by Django 5.0.1 on 2024-03-14 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_module_group_decentralization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='decentralization',
            name='function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.function'),
        ),
    ]
