# Generated by Django 5.0.1 on 2024-03-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_function_decentralization_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decentralization',
            name='function',
        ),
        migrations.RemoveField(
            model_name='decentralization',
            name='group',
        ),
        migrations.RemoveField(
            model_name='decentralization',
            name='module',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.DeleteModel(
            name='Decentralization',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
