# Generated by Django 5.0.1 on 2024-03-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_order_accept_alter_order_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='explanation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
