# Generated by Django 5.0.1 on 2024-03-25 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_order_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.state'),
        ),
    ]
