# Generated by Django 5.0.1 on 2024-03-25 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_category_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.state'),
        ),
        migrations.AddField(
            model_name='size',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.state'),
        ),
    ]
